apiVersion: v1
kind: Template
metadata:
  name: "apicast-guid-policy"
message: "3scale GUID Policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-guid-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-guid-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apicast-guid-policy:guid
    source:
      git:
        uri: ${GIT_REPO}
        ref: 'master'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'apicast-gateway-rhel8:3scale2.11'
          namespace: openshift

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-custom
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'amp-apicast:${AMP_RELEASE}'
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        - bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: 'apicast-guid-policy:guid'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/guid
            # copy also installed dependencies to the policy folder, so they are vendored
            # - destinationDir: policies/example/0.1/resty/
            #   sourcePath: /opt/app-root/src/lua_modules/share/lua/5.1/resty/iputils.lua
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src
        USER root

    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'apicast-gateway-rhel8:3scale2.11'
          namespace: openshift
      type: Docker
    triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: AMP_RELEASE
  description: The destination tag of your AMP release (eg. 2.11)
  value: '2.11' 
- name: GIT_REPO
  description: GIT REPO
  required: true